[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
LISTMONK_app__address = "0.0.0.0:${PORT}"
LISTMONK_db__ssl_mode = "require"
LISTMONK_db__max_open = "25"
LISTMONK_db__max_idle = "25"
LISTMONK_db__max_lifetime = "300s"
TZ = "Etc/UTC"
LISTMONK_ADMIN_USER = "admin"
LISTMONK_ADMIN_PASSWORD = "K9#mP2$vL7@nQ4!xR8"

# Database connection (Railway will set these automatically)
LISTMONK_db__host = "${PGHOST}"
LISTMONK_db__port = "${PGPORT}"
LISTMONK_db__user = "${PGUSER}"
LISTMONK_db__password = "${PGPASSWORD}"
LISTMONK_db__database = "${PGDATABASE}"
